services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: false

    Uknight\SteamAuthenticationBundle\Security\Authentication\Provider\SteamProvider: '@uknight.steam_authentication.security.authentication.provider.steam_provider'
    Uknight\SteamAuthenticationBundle\Security\Firewall\SteamListener: '@uknight.steam_authentication.security.firewall.steam_listener'
    Uknight\SteamAuthenticationBundle\Security\User\SteamUserProvider: '@uknight.steam_authentication.security.user.steam_user_provider'

    uknight.steam_authentication.factory.user_factory:
        class: Uknight\SteamAuthenticationBundle\Factory\UserFactory
        arguments:
            - '%uknight.steam_authentication.user_class%'
            - '%uknight.steam_authentication.fos%'

    uknight.steam_authentication.http.steam_api_client:
        class: Uknight\SteamAuthenticationBundle\Http\SteamApiClient
        arguments:
            - '%uknight.steam_authentication.api_key%'
        public: true

    uknight.steam_authentication.security.authentication.provider.steam_provider:
        class: Uknight\SteamAuthenticationBundle\Security\Authentication\Provider\SteamProvider
        arguments:
            - ''

    uknight.steam_authentication.security.firewall.steam_listener:
        class: Uknight\SteamAuthenticationBundle\Security\Firewall\SteamListener
        arguments:
            - '@security.authentication.manager'
            - '@router'
            - '%uknight.steam_authentication.login_redirect%'
            - '%uknight.steam_authentication.login_route%'
            - '@security.token_storage'

    uknight.steam_authentication.security.user.steam_user_provider:
        class: Uknight\SteamAuthenticationBundle\Security\User\SteamUserProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@uknight.steam_authentication.http.steam_api_client'
            - '%uknight.steam_authentication.user_class%'
            - '@uknight.steam_authentication.factory.user_factory'

    uknight.steam_authentication.twig.steam_extension:
        class: Uknight\SteamAuthenticationBundle\Twig\SteamExtension
        arguments:
            - '@router'
            - '%uknight.steam_authentication.login_route%'
        tags:
            - { name: twig.extension }